### ISSUE TITLE
Missing bfloat16 varlen kernel for Ada (sm_89) in flash-attn 2.8.4+cu132 Windows wheel causes "no kernel image" error

### ISSUE THREAD

**Issue by Ice-pumpkin** [sorryhyun/anima_lora#22]
This issue report was summarized by AI based on the debugging session, and edited by me.
Waiiit, there's a hotfix.. guess I'm really unlucky to alway stumble into trouble x3

---

**Environment**
```
- OS: Windows 11
- Python: 3.13
- PyTorch: 2.12.0+cu132
- CUDA Toolkit: 13.2
- GPU: NVIDIA GeForce RTX 4060 Laptop (Ada Lovelace, sm_89)
- flash-attn version: 2.8.4 (installed via `uv sync` from `sorryhyun/flash-attention-sm120-fix` wheel)
- Project: Anima LoRA training (preprocessing step)
```

**Issue**
Running `tasks.py preprocess` fails during text-embedding caching with `CUDA error: no kernel image is available for execution on the device`. The error originates from `flash_attn_varlen_func` when the input tensors are of dtype `torch.bfloat16`.

**How to reproduce (with original code)**
1. Activate the project virtual environment.
2. Run `tasks.py preprocess`.
3. The process will crash at the text-embedding caching stage. The error traceback (without any modifications) ends with:
```
torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
```
4. Alternatively, run the minimal reproduction script that does **not** require the full project:
```powershell
python -c "import torch; import flash_attn.flash_attn_interface as fa; q = torch.randn(1, 16, 64, device='cuda', dtype=torch.bfloat16); k = torch.randn(1, 16, 64, device='cuda', dtype=torch.bfloat16); v = torch.randn(1, 16, 64, device='cuda', dtype=torch.bfloat16); cu = torch.tensor([0,1], device='cuda', dtype=torch.int32); fa.flash_attn_varlen_func(q,k,v,cu,cu,512,512)"
```
This raises:
```
torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
```

**Optional debug prints to show tensor details**
If you want to see the exact tensor shapes and dtypes that trigger the error, add these lines in `library/anima/models.py`, inside the `LLMAdapterAttention.forward` method, right before the call to `attention_dispatch.flash_attn_varlen_func(...)` (line 2050):

```python
print("DEBUG flash_attn_varlen_func call:")
print("  q_packed shape:", q_packed.shape, "dtype:", q_packed.dtype)
print("  head_dim:", q_packed.shape[-1])
print("  max_seqlen_q:", L_q, "max_seqlen_k:", L_kv)
print("  cu_seqlens_q:", cu_seqlens_q)
print("  cu_seqlens_k:", cu_seqlens_kv)
```

With these prints, the output before the crash becomes:
```
DEBUG flash_attn_varlen_func call:
  q_packed shape: torch.Size([1, 16, 64]) dtype: torch.bfloat16
  head_dim: 64
  max_seqlen_q: 512 max_seqlen_k: 512
  cu_seqlens_q: tensor([0, 1], device='cuda:0', dtype=torch.int32)
  cu_seqlens_k: tensor([0, 1], device='cuda:0', dtype=torch.int32)
```

**Full original traceback (without debug prints)**
```
Traceback (most recent call last):
  File "...\scripts\preprocess\cache_text_embeddings.py", line 184, in <module>
    main()
  File "...\scripts\preprocess\cache_text_embeddings.py", line 128, in main
    stage_uncond_sidecar_with_models(...)
  File "...\library\inference\uncond.py", line 210, in stage_uncond_sidecar_with_models
    crossattn_emb, pooled = encode_uncond_with_models(...)
  File "...\library\inference\uncond.py", line 68, in encode_uncond_with_models
    crossattn_emb = llm_adapter(...)
  File "...\torch\nn\modules\module.py", line 1789, in _call_impl
    return forward_call(*args, **kwargs)
  File "...\library\anima\models.py", line 2243, in forward
    x = block(...)
  File "...\torch\nn\modules\module.py", line 1789, in _call_impl
    return forward_call(*args, **kwargs)
  File "...\library\anima\models.py", line 2145, in forward
    attn_out = self.self_attn(...)
  File "...\torch\nn\modules\module.py", line 1789, in _call_impl
    return forward_call(*args, **kwargs)
  File "...\library\anima\models.py", line 2058, in forward
    out_packed = attention_dispatch.flash_attn_varlen_func(...)
  File "...\flash_attn\flash_attn_interface.py", line 1464, in flash_attn_varlen_func
    return FlashAttnVarlenFunc.apply(...)
  File "...\torch\autograd\function.py", line 596, in apply
    return super().apply(*args, **kwargs)
  File "...\flash_attn\flash_attn_interface.py", line 946, in forward
    out_padded, softmax_lse, S_dmask, rng_state = _wrapped_flash_attn_varlen_forward(...)
  File "...\torch\_ops.py", line 1275, in __call__
    return self._op(*args, **kwargs)
  ...
  File "...\flash_attn\flash_attn_interface.py", line 177, in _flash_attn_varlen_forward
    out, softmax_lse, S_dmask, rng_state = flash_attn_gpu.varlen_fwd(...)
torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
```

**Verification that float16 works**
Using the exact same shapes but with `float16` instead of `bfloat16`, the call succeeds and returns an output:
```powershell
python -c "import torch; import flash_attn.flash_attn_interface as fa; q = torch.randn(1, 16, 64, device='cuda', dtype=torch.float16); k = torch.randn(1, 16, 64, device='cuda', dtype=torch.float16); v = torch.randn(1, 16, 64, device='cuda', dtype=torch.float16); cu = torch.tensor([0,1], device='cuda', dtype=torch.int32); out = fa.flash_attn_varlen_func(q,k,v,cu,cu,512,512); print('float16 success, shape:', out.shape)"
```
Output:
```
float16 success, shape: torch.Size([1, 16, 64])
```
This confirms the missing kernel is specific to **bfloat16**.

**Root cause**
The precompiled `flash-attn` wheel (2.8.4 from `sorryhyun/flash-attention-sm120-fix`, built for `cu132`) appears to be missing the **bfloat16 varlen attention kernel** for the Ada (sm_89) architecture.

**Workaround / Fix**
Installing a community-provided wheel that includes the bfloat16 kernel resolved the problem:
```
pip install https://github.com/mjun0812/flash-attention-prebuild-wheels/releases/download/v0.9.25/flash_attn-2.8.3+cu132torch2.12-cp313-cp313-win_amd64.whl
```
This demonstrates the missing kernel can be built successfully for CUDA 13.2 + sm_89.

I found  the wheel on https://mjunya.com/flash-attention-prebuild-wheels/

**Request**
- Please consider including the `bfloat16` varlen kernel for Ada GPUs in future CUDA 13.x Windows wheels.
- Alternatively, document the expected compute capability coverage for each wheel so users can check compatibility before installation.

**Comment by sorryhyun** [comment]
yep sorry for inconvenience. this was resolved as the exact solution you mentioned in v1.6.0.hotfix{1, 2} (both work)

**Comment by Ice-pumpkin** [comment]
Yeah. If only I can be one step faster.
I was trying to use @sjmind2's fork since they have the CAME optimizer, I've heard that it's better at learning the art style. 
I guess their base is your nightly, since I met the problem before 1.6.0 released, for about 2 days.

The training still have errors... I'm not sure if it exists in your version, I'll try when I have the time.
```
File "E:\Anima\anima_lora_sjmind2\anima_lora\train.py", line 2684, in <module>
File "E:\Anima\anima_lora_sjmind2\anima_lora\library\anima\models.py", line 1062, in _forward
File "E:\Anima\anima_lora_sjmind2\anima_lora\networks\attention_dispatch.py", line 222, in dispatch_attention
File "...\torch\nn\attention\flex_attention.py", line 2041, in flex_attention

torch._inductor.exc.InductorError: LoweringException: CalledProcessError: Command '['E:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\runtime\\tcc\\tcc.exe', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmp3997_3mu\\cuda_utils.c', '-O3', '-shared', '-Wno-psabi', '-o', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmp3997_3mu\\cuda_utils.cp313-win_amd64.pyd', '-fPIC', '-D_Py_USE_GCC_BUILTIN_ATOMICS', '-lcuda', '-lpython313', '-LE:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\lib', '-LC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\lib\\x64', '-LC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\libs', '-IE:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\include', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\include', '-I\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmp3997_3mu', '-IC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\Include']' returned non-zero exit status 1.
  target: flex_attention
```

**Comment by sorryhyun** [comment]
Thanks! I think it's because flex attention is working in different way somehow. If you verified the problem is resolved, please leave a comment!

**Comment by Ice-pumpkin** [comment]
I can start training after downgrading the triton-windows with `uv pip install triton-windows==3.6.0.post26`
Otherwise, even `python -c "from triton.runtime import driver; print(driver.active.get_current_target())"` will cause error.

There're still some flashing terminals, from the moment I click the "Train" button until a few minutes after the training actually kicks in (i.e., when the GPU starts humming), but I guess it's harmless.

**Comment by sorryhyun** [comment]
I guess you're on `torch==2.11` dependency. `triton-windows` should be `==3.7.0` if `torch==2.12` was paired.

**Comment by Ice-pumpkin** [comment]
I'm rather sure that `torch==2.12.0+cu132`, the version installed via `uv sync` without attempts to modify it.

<details>
<summary> uv pip freeze > requirements.txt </summary>

```text
absl-py==2.4.0
accelerate==1.13.0
adv-optm==2.2.3
aiohappyeyeballs==2.6.1
aiohttp==3.13.5
aiosignal==1.4.0
albucore==0.0.24
albumentations==2.0.8
alembic==1.18.4
-e file:///E:/Anima/anima_lora_sjmind2/anima_lora
annotated-doc==0.0.4
annotated-types==0.7.0
anyio==4.13.0
arrow==1.4.0
asgiref==3.11.1
attrs==26.1.0
av==17.0.1
beautifulsoup4==4.14.3
binaryornot==0.6.0
blake3==1.0.8
certifi==2026.2.25
charset-normalizer==3.4.7
click==8.3.2
colorama==0.4.6
comfy-aimdo==0.2.14
comfy-cli==1.7.3
comfy-kitchen==0.2.8
contourpy==1.3.3
cookiecutter==2.7.1
cycler==0.12.1
diffusers==0.37.1
einops==0.8.2
filelock==3.25.2
flash-attn @ https://github.com/mjun0812/flash-attention-prebuild-wheels/releases/download/v0.9.25/flash_attn-2.8.3+cu132torch2.12-cp313-cp313-win_amd64.whl
fonttools==4.62.1
frozenlist==1.8.0
fsspec==2026.3.0
ftfy==6.1.1
gitdb==4.0.12
gitpython==3.1.47
grpcio==1.80.0
h11==0.16.0
hf-xet==1.4.3
httpcore==1.0.9
httpx==0.28.1
huggingface-hub==1.9.0
idna==3.11
imagesize==2.0.0
importlib-metadata==9.0.0
iniconfig==2.3.0
iopath==0.1.10
jinja2==3.1.6
json-logic==0.7.0a0
kiwisolver==1.5.0
kornia==0.8.2
kornia-rs==0.1.10
lion-pytorch==0.2.4
mako==1.3.11
markdown==3.10.2
markdown-it-py==4.0.0
markdownify==1.2.2
markupsafe==3.0.2
matplotlib==3.10.8
mdurl==0.1.2
mixpanel==5.1.0
mpmath==1.3.0
multidict==6.7.1
networkx==3.6.1
numpy==2.4.4
opencv-python==4.11.0.86
opencv-python-headless==4.11.0.86
packaging==26.0
pathspec==1.1.1
pillow==12.2.0
pluggy==1.6.0
portalocker==3.2.0
prodigyopt==1.1.2
prompt-toolkit==3.0.52
propcache==0.4.1
protobuf==7.34.1
psutil==7.2.2
pycocotools==2.0.11
pydantic==2.12.5
pydantic-core==2.41.5
pydantic-settings==2.14.0
pygments==2.20.0
pyparsing==3.3.2
pyside6==6.11.0
pyside6-addons==6.11.0
pyside6-essentials==6.11.0
pytest==9.0.3
python-dateutil==2.9.0.post0
python-dotenv==1.2.2
python-slugify==8.0.4
pytorch-optimizer==3.10.0
pywin32==311
pyyaml==6.0.3
questionary==2.1.1
regex==2026.4.4
requests==2.33.1
rich==14.3.3
ruff==0.15.9
safetensors==0.7.0
sam3 @ git+https://github.com/facebookresearch/sam3@bfbed072a07a6a52c8d5fdc75a7a186251a835b1
schedulefree==1.4.1
scipy==1.17.1
segmentation-models-pytorch==0.5.0
semver==3.0.4
sentencepiece==0.2.1
setuptools==81.0.0
shellingham==1.5.4
shiboken6==6.11.0
simpleeval==1.0.7
simsimd==6.5.16
six==1.17.0
smmap==5.0.3
soupsieve==2.8.3
spandrel==0.4.2
sqlalchemy==2.1.0b2
stringzilla==4.6.0
sympy==1.14.0
tensorboard==2.20.0
tensorboard-data-server==0.7.2
text-unidecode==1.3
timm==1.0.26
tokenizers==0.22.2
toml==0.10.2
tomlkit==0.14.0
torch==2.12.0+cu132
torchsde==0.2.6
torchvision==0.27.0+cu132
tqdm==4.67.3
trampoline==0.1.2
transformers==5.5.0
triton-windows==3.6.0.post26
typer==0.24.1
typing-extensions==4.15.0
typing-inspection==0.4.2
tzdata==2026.2
urllib3==2.6.3
uv==0.11.7
voluptuous==0.16.0
wcwidth==0.6.0
websocket-client==1.9.0
werkzeug==3.1.8
yarl==1.23.0
zipp==3.23.0
</details> ```

**Comment by sorryhyun** [comment]
okay thanks. Does this occur only when using flex attention or flash attention too?

**Comment by Ice-pumpkin** [comment]
since even `python -c "from triton.runtime import driver; print(driver.active.get_current_target())"` will cause error

```
(anima-lora) PS E:\Anima\anima_lora_sjmind2\anima_lora> python -c "from triton.runtime import driver; print(driver.active.get_current_target())"
C:/Users/PumpkinIce/AppData/Local/Programs/Python/Python313/Include/cpython/pyatomic_gcc.h:63: error: '__ATOMIC_SEQ_CST' undeclared
Failed to compile. cc_cmd: ['E:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\runtime\\tcc\\tcc.exe', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpaqvmw_3w\\cuda_utils.c', '-O3', '-shared', '-Wno-psabi', '-o', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpaqvmw_3w\\cuda_utils.cp313-win_amd64.pyd', '-fPIC', '-D_Py_USE_GCC_BUILTIN_ATOMICS', '-lcuda', '-lpython313', '-LE:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\lib', '-LC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\lib\\x64', '-LC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\libs', '-IE:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\include', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\include', '-I\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpaqvmw_3w', '-IC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\Include']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from triton.runtime import driver; print(driver.active.get_current_target())
                                             ^^^^^^^^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\runtime\driver.py", line 39, in active
    self._active = self.default
                   ^^^^^^^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\runtime\driver.py", line 33, in default
    self._default = _create_driver()
                    ~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\runtime\driver.py", line 21, in _create_driver
    return active_drivers[0]()
           ~~~~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\backends\nvidia\driver.py", line 347, in __init__
    self.utils = CudaUtils()  # TODO: make static
                 ~~~~~~~~~^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\backends\nvidia\driver.py", line 77, in __init__
    mod = compile_module_from_src(
        src=Path(os.path.join(dirname, "driver.c")).read_text(),
    ...<3 lines>...
        libraries=libraries,
    )
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\runtime\build.py", line 188, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dirs or [], include_dirs or [], libraries or [], ccflags or [])
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\runtime\build.py", line 139, in _build
    raise e
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\runtime\build.py", line 136, in _build
    subprocess.check_call(cc_cmd)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\PumpkinIce\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 419, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['E:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\runtime\\tcc\\tcc.exe', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpaqvmw_3w\\cuda_utils.c', '-O3', '-shared', '-Wno-psabi', '-o', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpaqvmw_3w\\cuda_utils.cp313-win_amd64.pyd', '-fPIC', '-D_Py_USE_GCC_BUILTIN_ATOMICS', '-lcuda', '-lpython313', '-LE:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\lib', '-LC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\lib\\x64', '-LC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\libs', '-IE:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\include', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\include', '-I\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpaqvmw_3w', '-IC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\Include']' returned non-zero exit status 1.
</details> ```
```


I don't think it occur only when using flex attention. 
Here's the error info when running the default lora setting, which I think is using `flash`

<details>
<summary> Error output running default lora training </summary>

```text
正在向训练守护进程提交任务……
已将任务 20260527-084414-fbe59e 排入训练守护进程。
2026-05-27 08:44:20 INFO     Loading chain: base    presets/default     io.py:589
                             gui-methods/lora                                  
                    INFO     Config snapshot written:                 io.py:539
                             output/ckpt_12\anima_lora.snapshot.toml           
2026-05-27 08:44:21 INFO     Loading dataset config from          train.py:1432
                             configs/base.toml                                 
                    INFO     prepare images.                  dreambooth.py:371
                    INFO     get image size from name of      dreambooth.py:147
                             cache files                                       
                    INFO     set image size from cache files: dreambooth.py:201
                             51/51                                             
                    INFO     found directory                  dreambooth.py:244
                             post_image_dataset/image_dataset                  
                             /nametakenoko_rededup/.resized                    
                             contains 51 image files                           
                    INFO     51 train images with repeats.    dreambooth.py:447
                    INFO     0 reg images with repeats.       dreambooth.py:451
                    WARNING  no regularization images         dreambooth.py:456
                    INFO     [Dataset 0]                          loader.py:530
                               batch_size: 1                                   
                               resize_interpolation: None                      
                                                                               
                               [Subset 0 of Dataset 0]                         
                                 image_dir:                                    
                             "post_image_dataset/image_dataset/na              
                             metakenoko_rededup/.resized"                      
                                 image_count: 51                               
                                 num_repeats: 1                                
                                 sample_ratio: 1.0                             
                                 keep_tokens: 3                                
                                 caption_dropout_rate: 0.03                    
                                 caption_dropout_every_n_epochs:               
                             0                                                 
                                 caption_tag_dropout_rate: 0.0                 
                                 caption_prefix: None                          
                                 caption_suffix: None                          
                                 color_aug: False                              
                                 flip_aug: False                               
                                 face_crop_aug_range: None                     
                                 random_crop: False                            
                                 token_warmup_min: 1,                          
                                 token_warmup_step: 0,                         
                                 alpha_mask: False                             
                                 resize_interpolation: None                    
                                 custom_attributes: {}                         
                                 is_reg: False                                 
                                 class_tokens: None                            
                                 caption_extension: .txt                       
                                                                               
                    INFO     [Prepare dataset 0]                  loader.py:542
                    INFO     loading image sizes.                   base.py:435
                    INFO     make buckets                           base.py:440
                    INFO     number of images (including repeats)   base.py:466
                    INFO     bucket 0: resolution (768, 1344),      base.py:476
                             count: 1                                          
                    INFO     bucket 1: resolution (800, 1344),      base.py:476
                             count: 11                                         
                    INFO     bucket 2: resolution (896, 1152),      base.py:476
                             count: 3                                          
                    INFO     bucket 3: resolution (896, 1200),      base.py:476
                             count: 3                                          
                    INFO     bucket 4: resolution (1200, 896),      base.py:476
                             count: 12                                         
                    INFO     bucket 5: resolution (1344, 768),      base.py:476
                             count: 20                                         
                    INFO     bucket 6: resolution (1536, 1536),     base.py:476
                             count: 1                                          
                    INFO     mean ar error (without repeats): 0.0   base.py:484
                    INFO     caption dropout ENABLED --           train.py:1489
                             per-subset rates: [0.03]                          
                    INFO     preparing accelerator                train.py:2023
accelerator device: cuda
                    INFO     Skipping Qwen3 text encoder load: all train.py:453
                             text-encoder outputs cached.                      
                    INFO     Skipping VAE load: all latents cached train.py:472
                             and no sampling.                                  
                    INFO     [Dataset 0]                            group.py:59
                    INFO     caching latents with caching strategy. base.py:651
                    INFO     caching latents...                     base.py:705
                    INFO     [Dataset 0]                           group.py:111
                    INFO     caching Text Encoder outputs with      base.py:875
                             caching strategy.                                 
                    INFO     checking cache validity...             base.py:886
                    INFO     no Text Encoder outputs to cache       base.py:917
                    INFO     Using Flash Attention 2 (flash_attn   train.py:501
                             2.8.3)                                            
                    INFO     Loading Anima DiT model with          train.py:529
                             attn_softmax_scale: None...                       
                    INFO     Loading DiT model from              weights.py:167
                             E:\Anima\anima_lora_sjmind2\anima_l               
                             ora\models\diffusion_models\anima-b               
                             ase-v1.0.safetensors, device=cuda                 
                    INFO     Loading model files:             lora_utils.py:163
                             ['E:\\Anima\\anima_lora_sjmind2\                  
                             \anima_lora\\models\\diffusion_m                  
                             odels\\anima-base-v1.0.safetenso                  
                             rs']                                              
                    INFO     Loading state dict. Dtype of     lora_utils.py:406
                             weight: torch.bfloat16, hook                      
                             enabled: False                                    
                                                                                       
2026-05-27 08:44:24 INFO     Loaded DiT model from               weights.py:210
                             E:\Anima\anima_lora_sjmind2\anima_l               
                             ora\models\diffusion_models\anima-b               
                             ase-v1.0.safetensors, unexpected                  
                             missing keys: 0, unexpected keys: 0               
Anima: native_flatten on, 5 token-count families (cache_size_limit=18); compiled 28 block._forward with backend=inductor, mode=None
2026-05-27 08:44:25 INFO     caption dropout uncond loaded:        train.py:657
                             post_image_dataset\_anima_uncond_te.s             
                             afetensors shape=(1, 512, 1024)                   
import network module: networks.lora_anima
                    INFO     create LoRA network. base dim       network.py:511
                             (rank): 32, alpha: 32.0                           
                    INFO     neuron dropout: p=None, rank        network.py:514
                             dropout: p=None, module dropout:                  
                             p=None                                            
                                                                     
2026-05-27 08:44:26 INFO     create LoRA for Anima DiT: 196      network.py:928
                             modules.                                          
                    INFO     use_custom_down_autograd: enabled   factory.py:137
                             on 196 LoRA-family modules (saves                 
                             ~32-128 MiB/Linear of fp32                        
                             activation per step)                              
                    INFO     enable LoRA for DiT: 196 modules   network.py:2716
prepare optimizer, data loader etc.
                    INFO     use AdamW optimizer | {'fused':  optimizers.py:348
                             True}                                             
override steps. steps for 2 epochs is
running training
  num train images * repeats
  num validation images * repeats
  num reg images
  num batches per epoch
  num epochs
  batch size per device
  gradient accumulation steps
  total optimization steps
2026-05-27 08:44:31 INFO     text_encoder is not needed for         loop.py:155
                             training. deleting to save memory.                
2026-05-27 08:44:32 INFO     unet dtype: torch.bfloat16, device:    loop.py:215
                             cuda:0                                            
                    INFO     sigma sampling:                        loop.py:224
                             timestep_sampling=sigmoid,                        
                             sigmoid_scale=1.0, sigmoid_bias=0.0               
epoch 1/2
W0527 08:44:44.191000 17728 .venv\Lib\site-packages\torch\_inductor\utils.py:1717] [0/0] Not enough SMs to use max_autotune_gemm mode
Failed to compile. cc_cmd: ['E:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\runtime\\tcc\\tcc.exe', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpfmha1wj2\\cuda_utils.c', '-O3', '-shared', '-Wno-psabi', '-o', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpfmha1wj2\\cuda_utils.cp313-win_amd64.pyd', '-fPIC', '-D_Py_USE_GCC_BUILTIN_ATOMICS', '-lcuda', '-lpython313', '-LE:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\lib', '-LC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\lib\\x64', '-LC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\libs', '-IE:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\include', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\include', '-I\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpfmha1wj2', '-IC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\Include']
Traceback (most recent call last):
  File "E:\Anima\anima_lora_sjmind2\anima_lora\train.py", line 2685, in <module>
    trainer.train(args)
    ~~~~~~~~~~~~~^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\train.py", line 2365, in train
    run_training_loop(self, loop_state)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\library\training\loop.py", line 463, in run_training_loop
    pending_prefetch = _run_epoch_steps(
        trainer, state, epoch, prefetch=pending_prefetch
    )
  File "E:\Anima\anima_lora_sjmind2\anima_lora\library\training\loop.py", line 590, in _run_epoch_steps
    loss = _run_step(trainer, state, batch)
  File "E:\Anima\anima_lora_sjmind2\anima_lora\library\training\loop.py", line 677, in _run_step
    loss = trainer.process_batch(state.train_ctx, batch, is_train=True)
  File "E:\Anima\anima_lora_sjmind2\anima_lora\train.py", line 1019, in process_batch
    return self._process_batch_inner(ctx, batch, is_train=is_train)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\train.py", line 1133, in _process_batch_inner
    noise_pred, target, timesteps, weighting = self.get_noise_pred_and_target(
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        ctx,
        ^^^^
    ...<3 lines>...
        is_train=is_train,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\train.py", line 837, in get_noise_pred_and_target
    model_pred = anima(
        noisy_model_input,
    ...<3 lines>...
        **kw,
    )
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1778, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1789, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\accelerate\utils\operations.py", line 823, in forward
    return model_forward(*args, **kwargs)
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\accelerate\utils\operations.py", line 811, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
                           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\amp\autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
  File "E:\Anima\anima_lora_sjmind2\anima_lora\library\anima\models.py", line 1829, in forward
    return self.forward_mini_train_dit(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        x,
        ^^
    ...<7 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\library\anima\models.py", line 1784, in forward_mini_train_dit
    x_B_T_H_W_D = self._run_blocks(
        x_B_T_H_W_D,
    ...<3 lines>...
        **block_kwargs,
    )
  File "E:\Anima\anima_lora_sjmind2\anima_lora\library\anima\models.py", line 1618, in _run_blocks
    x = block(
        x,
    ...<3 lines>...
        **block_kwargs,
    )
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1778, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1789, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Anima\anima_lora_sjmind2\anima_lora\library\anima\models.py", line 1152, in forward
    return self._forward(
           ~~~~~~~~~~~~~^
        x_B_T_H_W_D,
        ^^^^^^^^^^^^
    ...<4 lines>...
        adaln_lora_B_T_3D,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_dynamo\eval_frame.py", line 1062, in compile_wrapper
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1069, in _compile_fx_inner
    raise InductorError(e, currentframe()).with_traceback(
        e.__traceback__
    ) from None
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1049, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
        gm,
    ...<3 lines>...
        **graph_kwargs,
    )
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1836, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1597, in codegen_and_compile
    compiled_module = graph.compile_to_module()
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\graph.py", line 2613, in compile_to_module
    return self._compile_to_module()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\graph.py", line 2619, in _compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
                                                             ~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\graph.py", line 2555, in codegen
    self.scheduler.codegen()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\scheduler.py", line 7350, in codegen
    self._codegen_partitions()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\scheduler.py", line 7490, in _codegen_partitions
    self._codegen(partition)
    ~~~~~~~~~~~~~^^^^^^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\scheduler.py", line 7641, in _codegen
    self.get_backend(device).codegen_node(node)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\codegen\cuda_combined_scheduling.py", line 152, in codegen_node
    return self._triton_scheduling.codegen_node(node)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\codegen\simd.py", line 1864, in codegen_node
    return self._codegen_nodes(nodes, coalesce_analysis)  # type: ignore[arg-type]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\codegen\simd.py", line 1837, in _codegen_nodes
    return self.codegen_node_schedule(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        SIMDKernelFeatures(node_schedule, numel, rnumel, coalesce_analysis)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\codegen\simd.py", line 1961, in codegen_node_schedule
    src_code = kernel.codegen_kernel()
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\codegen\triton.py", line 5760, in codegen_kernel
    **self.inductor_meta_common(),
      ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\_inductor\codegen\triton.py", line 5568, in inductor_meta_common
    "backend_hash": torch.utils._triton.triton_hash_with_backend(),
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\utils\_triton.py", line 219, in triton_hash_with_backend
    backend = triton_backend()
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\torch\utils\_triton.py", line 193, in triton_backend
    target = driver.active.get_current_target()
             ^^^^^^^^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\runtime\driver.py", line 39, in active
    self._active = self.default
                   ^^^^^^^^^^^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\runtime\driver.py", line 33, in default
    self._default = _create_driver()
                    ~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\runtime\driver.py", line 21, in _create_driver
    return active_drivers[0]()
           ~~~~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\backends\nvidia\driver.py", line 347, in __init__
    self.utils = CudaUtils()  # TODO: make static
                 ~~~~~~~~~^^
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\backends\nvidia\driver.py", line 77, in __init__
    mod = compile_module_from_src(
        src=Path(os.path.join(dirname, "driver.c")).read_text(),
    ...<3 lines>...
        libraries=libraries,
    )
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\runtime\build.py", line 188, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dirs or [], include_dirs or [], libraries or [], ccflags or [])
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\runtime\build.py", line 139, in _build
    raise e
  File "E:\Anima\anima_lora_sjmind2\anima_lora\.venv\Lib\site-packages\triton\runtime\build.py", line 136, in _build
    subprocess.check_call(cc_cmd)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\PumpkinIce\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 419, in check_call
    raise CalledProcessError(retcode, cmd)
torch._inductor.exc.InductorError: CalledProcessError: Command '['E:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\runtime\\tcc\\tcc.exe', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpfmha1wj2\\cuda_utils.c', '-O3', '-shared', '-Wno-psabi', '-o', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpfmha1wj2\\cuda_utils.cp313-win_amd64.pyd', '-fPIC', '-D_Py_USE_GCC_BUILTIN_ATOMICS', '-lcuda', '-lpython313', '-LE:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\lib', '-LC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\lib\\x64', '-LC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\libs', '-IE:\\Anima\\anima_lora_sjmind2\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\include', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\include', '-I\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpfmha1wj2', '-IC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\Include']' returned non-zero exit status 1.
Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

**Comment by sorryhyun** [comment]
Would you check does turning off `torch_compile` in `base.toml` makes training work? That would narrow the problems.

**Comment by Ice-pumpkin** [comment]
Yes, turning off `torch_compile` (toggling the switch off in the GUI's Advance-performance-torch_compile) makes training work, and with it on would produce the very same `torch._inductor.exc.InductorError: CalledProcessError` error.
And I'm using your version this time, after `make update`.

<details>
<summary> Error output running default tlora training with torch_compile off</summary>

```text
Submitting job to the training daemon…
Queued job 20260527-155737-e57023 on the training daemon.
2026-05-27 15:58:05 INFO     Loading chain: base    presets/default     io.py:594
                             gui-methods/tlora                                 
                    INFO     Config snapshot written:                 io.py:544
                             output/ckpt\anima_tlora_ortho.snapshot.t          
                             oml                                               
2026-05-27 15:58:06 INFO     Loading dataset config from          train.py:1432
                             configs/base.toml                                 
                    INFO     prepare images.                  dreambooth.py:361
                    INFO     get image size from name of      dreambooth.py:147
                             cache files                                       
                    INFO     set image size from cache files: dreambooth.py:191
                             0/117                                             
                    INFO     found directory                  dreambooth.py:234
                             post_image_dataset/resized                        
                             contains 117 image files                          
                    INFO     117 train images with repeats.   dreambooth.py:437
                    INFO     0 reg images with repeats.       dreambooth.py:441
                    WARNING  no regularization images         dreambooth.py:446
                    INFO     [Dataset 0]                          loader.py:530
                               batch_size: 1                                   
                               resize_interpolation: None                      
                                                                               
                               [Subset 0 of Dataset 0]                         
                                 image_dir:                                    
                             "post_image_dataset/resized"                      
                                 image_count: 117                              
                                 num_repeats: 1                                
                                 sample_ratio: 1.0                             
                                 keep_tokens: 3                                
                                 caption_dropout_rate: 0.1                     
                                 caption_dropout_every_n_epochs:               
                             0                                                 
                                 caption_tag_dropout_rate: 0.0                 
                                 caption_prefix: None                          
                                 caption_suffix: None                          
                                 color_aug: False                              
                                 flip_aug: False                               
                                 face_crop_aug_range: None                     
                                 random_crop: False                            
                                 token_warmup_min: 1,                          
                                 token_warmup_step: 0,                         
                                 alpha_mask: False                             
                                 resize_interpolation: None                    
                                 custom_attributes: {}                         
                                 is_reg: False                                 
                                 class_tokens: None                            
                                 caption_extension: .txt                       
                                                                               
                    INFO     [Prepare dataset 0]                  loader.py:542
                    INFO     loading image sizes.                   base.py:435
                    INFO     make buckets                           base.py:440
                    INFO     number of images (including repeats)   base.py:466
                    INFO     bucket 0: resolution (640, 1680),      base.py:476
                             count: 1                                          
                    INFO     bucket 1: resolution (768, 1344),      base.py:476
                             count: 1                                          
                    INFO     bucket 2: resolution (800, 1344),      base.py:476
                             count: 1                                          
                    INFO     bucket 3: resolution (896, 1152),      base.py:476
                             count: 1                                          
                    INFO     bucket 4: resolution (896, 1200),      base.py:476
                             count: 3                                          
                    INFO     bucket 5: resolution (1008, 1024),     base.py:476
                             count: 2                                          
                    INFO     bucket 6: resolution (1024, 1008),     base.py:476
                             count: 2                                          
                    INFO     bucket 7: resolution (1152, 896),      base.py:476
                             count: 106                                        
                    INFO     mean ar error (without repeats): 0.0   base.py:484
                    INFO     caption dropout ENABLED --           train.py:1489
                             per-subset rates: [0.1]                           
                    INFO     preparing accelerator                train.py:2023
accelerator device: cuda
2026-05-27 15:58:07 INFO     Skipping Qwen3 text encoder load: all train.py:453
                             text-encoder outputs cached.                      
                    INFO     Skipping VAE load: all latents cached train.py:472
                             and no sampling.                                  
                    INFO     [Dataset 0]                            group.py:59
                    INFO     caching latents with caching strategy. base.py:651
                    INFO     caching latents...                     base.py:705
                    INFO     [Dataset 0]                           group.py:111
                    INFO     caching Text Encoder outputs with      base.py:875
                             caching strategy.                                 
                    INFO     checking cache validity...             base.py:886
                    INFO     no Text Encoder outputs to cache       base.py:917
                    INFO     Using Flash Attention 2 (flash_attn   train.py:501
                             2.8.3)                                            
                    INFO     Loading Anima DiT model with          train.py:529
                             attn_softmax_scale: None...                       
                    INFO     Loading DiT model from              weights.py:167
                             E:\Anima\anima_lora\models\diffusio               
                             n_models\anima-base-v1.0.safetensor               
                             s, device=cuda                                    
                    INFO     Loading model files:             lora_utils.py:163
                             ['E:\\Anima\\anima_lora\\models\                  
                             \diffusion_models\\anima-base-v1                  
                             .0.safetensors']                                  
                    INFO     Loading state dict. Dtype of     lora_utils.py:320
                             weight: torch.bfloat16, hook                      
                             enabled: False                                    
                                                                                       
2026-05-27 15:58:10 INFO     Loaded DiT model from               weights.py:210
                             E:\Anima\anima_lora\models\diffusio               
                             n_models\anima-base-v1.0.safetensor               
                             s, unexpected missing keys: 0,                    
                             unexpected keys: 0                                
Anima: native_flatten on, 2 token-count families (cache_size_limit=12); compiled 28 block._forward with backend=inductor, mode=None
2026-05-27 15:58:18 INFO     caption dropout uncond loaded:        train.py:657
                             post_image_dataset\_anima_uncond_te.s             
                             afetensors shape=(1, 512, 1024)                   
import network module: networks.lora_anima
                    INFO     create LoRA network. base dim       network.py:503
                             (rank): 32, alpha: 32.0                           
                    INFO     neuron dropout: p=None, rank        network.py:506
                             dropout: p=None, module dropout:                  
                             p=None                                            
                                                                     
2026-05-27 15:58:19 INFO     create LoRA for Anima DiT: 196      network.py:903
                             modules.                                          
                    INFO     use_custom_down_autograd: enabled   factory.py:135
                             on 196 LoRA-family modules (saves                 
                             ~32-128 MiB/Linear of fp32                        
                             activation per step)                              
                    INFO     Timestep-dependent rank masking:    factory.py:142
                             min_rank=8, alpha=1.0                             
                    INFO     OrthoLoRA: Cayley parameterization  factory.py:219
                             + SVD-informed init                               
                    INFO     enable LoRA for DiT: 196 modules   network.py:2689
prepare optimizer, data loader etc.
                    INFO     use AdamW optimizer | {'fused':  optimizers.py:278
                             True}                                             
override steps. steps for 4 epochs is
running training
  num train images * repeats
  num validation images * repeats
  num reg images
  num batches per epoch
  num epochs
  batch size per device
  gradient accumulation steps
  total optimization steps
fatal: not a git repository (or any of the parent directories): .git
2026-05-27 15:58:24 INFO     text_encoder is not needed for         loop.py:153
                             training. deleting to save memory.                
                    INFO     unet dtype: torch.bfloat16, device:    loop.py:213
                             cuda:0                                            
                    INFO     sigma sampling:                        loop.py:222
                             timestep_sampling=sigmoid,                        
                             sigmoid_scale=1.0, sigmoid_bias=0.0               
epoch 1/4
W0527 15:58:45.216000 12540 .venv\Lib\site-packages\torch\_inductor\utils.py:1717] [0/0] Not enough SMs to use max_autotune_gemm mode
Failed to compile. cc_cmd: ['E:\\Anima\\anima_lora\\.venv\\Lib\\site-packages\\triton\\runtime\\tcc\\tcc.exe', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpyi7i6e_a\\cuda_utils.c', '-O3', '-shared', '-Wno-psabi', '-o', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpyi7i6e_a\\cuda_utils.cp313-win_amd64.pyd', '-fPIC', '-D_Py_USE_GCC_BUILTIN_ATOMICS', '-lcuda', '-lpython313', '-LE:\\Anima\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\lib', '-LC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\lib\\x64', '-LC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\libs', '-IE:\\Anima\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\include', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\include', '-I\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpyi7i6e_a', '-IC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\Include']
Traceback (most recent call last):
  File "E:\Anima\anima_lora\train.py", line 2685, in <module>
    trainer.train(args)
    ~~~~~~~~~~~~~^^^^^^
  File "E:\Anima\anima_lora\train.py", line 2365, in train
    run_training_loop(self, loop_state)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora\library\training\loop.py", line 328, in run_training_loop
    _run_epoch_steps(trainer, state, epoch)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora\library\training\loop.py", line 380, in _run_epoch_steps
    loss = _run_step(trainer, state, batch)
  File "E:\Anima\anima_lora\library\training\loop.py", line 448, in _run_step
    loss = trainer.process_batch(state.train_ctx, batch, is_train=True)
  File "E:\Anima\anima_lora\train.py", line 1019, in process_batch
    return self._process_batch_inner(ctx, batch, is_train=is_train)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora\train.py", line 1133, in _process_batch_inner
    noise_pred, target, timesteps, weighting = self.get_noise_pred_and_target(
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        ctx,
        ^^^^
    ...<3 lines>...
        is_train=is_train,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\Anima\anima_lora\train.py", line 837, in get_noise_pred_and_target
    model_pred = anima(
        noisy_model_input,
    ...<3 lines>...
        **kw,
    )
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1778, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1789, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\accelerate\utils\operations.py", line 823, in forward
    return model_forward(*args, **kwargs)
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\accelerate\utils\operations.py", line 811, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
                           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\amp\autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
  File "E:\Anima\anima_lora\library\anima\models.py", line 1829, in forward
    return self.forward_mini_train_dit(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        x,
        ^^
    ...<7 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "E:\Anima\anima_lora\library\anima\models.py", line 1784, in forward_mini_train_dit
    x_B_T_H_W_D = self._run_blocks(
        x_B_T_H_W_D,
    ...<3 lines>...
        **block_kwargs,
    )
  File "E:\Anima\anima_lora\library\anima\models.py", line 1618, in _run_blocks
    x = block(
        x,
    ...<3 lines>...
        **block_kwargs,
    )
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1778, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1789, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Anima\anima_lora\library\anima\models.py", line 1152, in forward
    return self._forward(
           ~~~~~~~~~~~~~^
        x_B_T_H_W_D,
        ^^^^^^^^^^^^
    ...<4 lines>...
        adaln_lora_B_T_3D,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_dynamo\eval_frame.py", line 1062, in compile_wrapper
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1069, in _compile_fx_inner
    raise InductorError(e, currentframe()).with_traceback(
        e.__traceback__
    ) from None
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1049, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
        gm,
    ...<3 lines>...
        **graph_kwargs,
    )
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1836, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1597, in codegen_and_compile
    compiled_module = graph.compile_to_module()
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\graph.py", line 2613, in compile_to_module
    return self._compile_to_module()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\graph.py", line 2619, in _compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
                                                             ~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\graph.py", line 2555, in codegen
    self.scheduler.codegen()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\scheduler.py", line 7350, in codegen
    self._codegen_partitions()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\scheduler.py", line 7490, in _codegen_partitions
    self._codegen(partition)
    ~~~~~~~~~~~~~^^^^^^^^^^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\scheduler.py", line 7641, in _codegen
    self.get_backend(device).codegen_node(node)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\codegen\cuda_combined_scheduling.py", line 152, in codegen_node
    return self._triton_scheduling.codegen_node(node)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\codegen\simd.py", line 1864, in codegen_node
    return self._codegen_nodes(nodes, coalesce_analysis)  # type: ignore[arg-type]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\codegen\simd.py", line 1837, in _codegen_nodes
    return self.codegen_node_schedule(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        SIMDKernelFeatures(node_schedule, numel, rnumel, coalesce_analysis)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\codegen\simd.py", line 1961, in codegen_node_schedule
    src_code = kernel.codegen_kernel()
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\codegen\triton.py", line 5760, in codegen_kernel
    **self.inductor_meta_common(),
      ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\_inductor\codegen\triton.py", line 5568, in inductor_meta_common
    "backend_hash": torch.utils._triton.triton_hash_with_backend(),
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\utils\_triton.py", line 219, in triton_hash_with_backend
    backend = triton_backend()
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\torch\utils\_triton.py", line 193, in triton_backend
    target = driver.active.get_current_target()
             ^^^^^^^^^^^^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\triton\runtime\driver.py", line 39, in active
    self._active = self.default
                   ^^^^^^^^^^^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\triton\runtime\driver.py", line 33, in default
    self._default = _create_driver()
                    ~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\triton\runtime\driver.py", line 21, in _create_driver
    return active_drivers[0]()
           ~~~~~~~~~~~~~~~~~^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\triton\backends\nvidia\driver.py", line 347, in __init__
    self.utils = CudaUtils()  # TODO: make static
                 ~~~~~~~~~^^
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\triton\backends\nvidia\driver.py", line 77, in __init__
    mod = compile_module_from_src(
        src=Path(os.path.join(dirname, "driver.c")).read_text(),
    ...<3 lines>...
        libraries=libraries,
    )
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\triton\runtime\build.py", line 188, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dirs or [], include_dirs or [], libraries or [], ccflags or [])
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\triton\runtime\build.py", line 139, in _build
    raise e
  File "E:\Anima\anima_lora\.venv\Lib\site-packages\triton\runtime\build.py", line 136, in _build
    subprocess.check_call(cc_cmd)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\PumpkinIce\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 419, in check_call
    raise CalledProcessError(retcode, cmd)
torch._inductor.exc.InductorError: CalledProcessError: Command '['E:\\Anima\\anima_lora\\.venv\\Lib\\site-packages\\triton\\runtime\\tcc\\tcc.exe', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpyi7i6e_a\\cuda_utils.c', '-O3', '-shared', '-Wno-psabi', '-o', '\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpyi7i6e_a\\cuda_utils.cp313-win_amd64.pyd', '-fPIC', '-D_Py_USE_GCC_BUILTIN_ATOMICS', '-lcuda', '-lpython313', '-LE:\\Anima\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\lib', '-LC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\lib\\x64', '-LC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\libs', '-IE:\\Anima\\anima_lora\\.venv\\Lib\\site-packages\\triton\\backends\\nvidia\\include', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\include', '-I\\\\?\\C:\\Users\\PUMPKI~1\\AppData\\Local\\Temp\\tmpyi7i6e_a', '-IC:\\Users\\PumpkinIce\\AppData\\Local\\Programs\\Python\\Python313\\Include']' returned non-zero exit status 1.
Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

**Comment by sorryhyun** [comment]
I think that's because of missing `cl.exe`, MSVC (Visual studio build tools) or missing PATH toward it. Any compilation error except for that should be raised before this, since the way how we compile the model is quite introductory.

**Comment by Ice-pumpkin** [comment]
In `Developer Command Prompt for VS 2022`:
```
C:\Program Files\Microsoft Visual Studio\2022\Community>where cl
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\bin\Hostx86\x86\cl.exe
```
so I have `cl.exe`

Though indeed `cl` in powershell (where `make gui`) doesn't work. mayybe it's a missing path problem.
But anyway, since `uv pip install triton-windows==3.6.0.post26` fix the problem I'll just let it pass, for now.

**Comment by sorryhyun** [comment]
I see. sorry again for I couldnt help, especially for 1.6.0 failures. Still I have tested several times and it works now, so please leave something here if compilation issue while using fa2 in Windows happen in different way.
